#!/bin/bash
echo "=== Chinese Traditional Wisdom AI Agent Workflow - Setup ==="
echo ""
echo "[1/3] Installing Python dependencies..."
pip3 install -r requirements.txt 2>/dev/null || pip install -r requirements.txt 2>/dev/null || echo "WARNING: pip install failed"
echo ""
echo "[2/3] Setup complete!"
echo ""
echo "Quick start:"
echo "  python scripts/bazi_calc.py 1990-05-15 --gender male --hour 15"
echo "  python scripts/yunqi_calc.py 2026"
echo "  python scripts/full_consultation.py 1990-05-15"
echo ""
echo "Or run the Web Dashboard: cd apps/visual && pnpm dev"
